Karla De La Cruz Valencia A01738420

# **Actividad de Numpy**

In [1]:
import numpy as np

1. Crear un arreglo de 10 cincos

In [2]:
arr_cincos = np.full(10, 5)
print(arr_cincos)

[5 5 5 5 5 5 5 5 5 5]


2. Crear un arreglo de enteros pares desde 10 hasta 50, inclusive

In [3]:
arr_pares = np.arange(10, 51, 2)
print(arr_pares)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


3. Crear una matriz cuadrada de 4x4 de números enteros aleatorios

In [4]:
matriz_aleatoria = np.random.randint(1, 10, size=(4, 4))
print(matriz_aleatoria)

[[5 7 3 6]
 [5 8 9 5]
 [9 4 4 9]
 [6 7 4 9]]


4. Generar un arreglo de 10 números aleatorios entre 0 y 1 y calcular la suma de todos sus elementos

In [7]:
arr_random_1 = np.random.rand(10)
suma = np.sum(arr_random_1)
print("Arreglo", arr_random_1, "\nSuma:", suma)


Arreglo [0.59354827 0.55407116 0.28877471 0.40470106 0.78304647 0.57355114
 0.69457257 0.31227926 0.96382956 0.00467786] 
Suma: 5.173052060872307


 5. Generar un arreglo de 10 números aleatorios entre 0 y 1 y calcular su media

In [6]:
arr_random_2 = np.random.rand(10)
media = np.mean(arr_random_2)
print("Arreglo:", arr_random_2, "\nMedia:", media)

Arreglo: [0.14874017 0.01716984 0.64971384 0.84705594 0.02024079 0.68815684
 0.939663   0.1284107  0.38673752 0.28106515] 
Media: 0.4106953782665651
